/**
 * HFPA 시간대/불량별 집계 DAO
 *
 * 파라미터:
 * - plant_cd      : 필수
 * - inspect_date  : 필수 (YYYYMMDD)
 * - work_center   : 필수
 * - line_cd       : 필수
 *
 * 결과 컬럼:
 * - div        : 구분(불량명, 'Defect Total', 'Defective Rate', ...)
 * - "H_00"~"H_23": 시간대별 값 (문자)
 * - "TOTAL"      : 합계 (문자)
 */
export async function findHfpaDashboard(
  client,
  { plant_cd, inspect_date, work_center, line_cd }
) {
  if (!plant_cd || !inspect_date || !work_center || !line_cd) {
    throw new Error("plant_cd, inspect_date, work_center, line_cd are required");
  }

  const params = [plant_cd, inspect_date, work_center, line_cd];

  const sql = `
WITH INSP_DATA AS (
    SELECT
        SUM(QTY_00H) AS INSP_00H, SUM(QTY_01H) AS INSP_01H, SUM(QTY_02H) AS INSP_02H, SUM(QTY_03H) AS INSP_03H,
        SUM(QTY_04H) AS INSP_04H, SUM(QTY_05H) AS INSP_05H, SUM(QTY_06H) AS INSP_06H, SUM(QTY_07H) AS INSP_07H,
        SUM(QTY_08H) AS INSP_08H, SUM(QTY_09H) AS INSP_09H, SUM(QTY_10H) AS INSP_10H, SUM(QTY_11H) AS INSP_11H,
        SUM(QTY_12H) AS INSP_12H, SUM(QTY_13H) AS INSP_13H, SUM(QTY_14H) AS INSP_14H, SUM(QTY_15H) AS INSP_15H,
        SUM(QTY_16H) AS INSP_16H, SUM(QTY_17H) AS INSP_17H, SUM(QTY_18H) AS INSP_18H, SUM(QTY_19H) AS INSP_19H,
        SUM(QTY_20H) AS INSP_20H, SUM(QTY_21H) AS INSP_21H, SUM(QTY_22H) AS INSP_22H, SUM(QTY_23H) AS INSP_23H,
        (
            SUM(COALESCE(QTY_00H,0)) + SUM(COALESCE(QTY_01H,0)) + SUM(COALESCE(QTY_02H,0)) + SUM(COALESCE(QTY_03H,0)) +
            SUM(COALESCE(QTY_04H,0)) + SUM(COALESCE(QTY_05H,0)) + SUM(COALESCE(QTY_06H,0)) + SUM(COALESCE(QTY_07H,0)) +
            SUM(COALESCE(QTY_08H,0)) + SUM(COALESCE(QTY_09H,0)) + SUM(COALESCE(QTY_10H,0)) + SUM(COALESCE(QTY_11H,0)) +
            SUM(COALESCE(QTY_12H,0)) + SUM(COALESCE(QTY_13H,0)) + SUM(COALESCE(QTY_14H,0)) + SUM(COALESCE(QTY_15H,0)) +
            SUM(COALESCE(QTY_16H,0)) + SUM(COALESCE(QTY_17H,0)) + SUM(COALESCE(QTY_18H,0)) + SUM(COALESCE(QTY_19H,0)) +
            SUM(COALESCE(QTY_20H,0)) + SUM(COALESCE(QTY_21H,0)) + SUM(COALESCE(QTY_22H,0)) + SUM(COALESCE(QTY_23H,0))
        ) AS INSP_TOTAL
    FROM (
        SELECT
            CASE WHEN HOUR_CD = '00' THEN QTY END AS QTY_00H,
            CASE WHEN HOUR_CD = '01' THEN QTY END AS QTY_01H,
            CASE WHEN HOUR_CD = '02' THEN QTY END AS QTY_02H,
            CASE WHEN HOUR_CD = '03' THEN QTY END AS QTY_03H,
            CASE WHEN HOUR_CD = '04' THEN QTY END AS QTY_04H,
            CASE WHEN HOUR_CD = '05' THEN QTY END AS QTY_05H,
            CASE WHEN HOUR_CD = '06' THEN QTY END AS QTY_06H,
            CASE WHEN HOUR_CD = '07' THEN QTY END AS QTY_07H,
            CASE WHEN HOUR_CD = '08' THEN QTY END AS QTY_08H,
            CASE WHEN HOUR_CD = '09' THEN QTY END AS QTY_09H,
            CASE WHEN HOUR_CD = '10' THEN QTY END AS QTY_10H,
            CASE WHEN HOUR_CD = '11' THEN QTY END AS QTY_11H,
            CASE WHEN HOUR_CD = '12' THEN QTY END AS QTY_12H,
            CASE WHEN HOUR_CD = '13' THEN QTY END AS QTY_13H,
            CASE WHEN HOUR_CD = '14' THEN QTY END AS QTY_14H,
            CASE WHEN HOUR_CD = '15' THEN QTY END AS QTY_15H,
            CASE WHEN HOUR_CD = '16' THEN QTY END AS QTY_16H,
            CASE WHEN HOUR_CD = '17' THEN QTY END AS QTY_17H,
            CASE WHEN HOUR_CD = '18' THEN QTY END AS QTY_18H,
            CASE WHEN HOUR_CD = '19' THEN QTY END AS QTY_19H,
            CASE WHEN HOUR_CD = '20' THEN QTY END AS QTY_20H,
            CASE WHEN HOUR_CD = '21' THEN QTY END AS QTY_21H,
            CASE WHEN HOUR_CD = '22' THEN QTY END AS QTY_22H,
            CASE WHEN HOUR_CD = '23' THEN QTY END AS QTY_23H
        FROM (
            SELECT HOUR_CD, COUNT(*) AS QTY
            FROM quality.dmqm_hfpa_crtn
            WHERE PLANT_CD = $1
              AND INSPECT_DATE = $2
              AND work_center = $3
              AND line_cd = $4
            GROUP BY HOUR_CD
        ) AS t
    ) AS x
),
DEFECTIVE_DATA AS (
    SELECT
        SUM(QTY_00H) AS INSP_00H, SUM(QTY_01H) AS INSP_01H, SUM(QTY_02H) AS INSP_02H, SUM(QTY_03H) AS INSP_03H,
        SUM(QTY_04H) AS INSP_04H, SUM(QTY_05H) AS INSP_05H, SUM(QTY_06H) AS INSP_06H, SUM(QTY_07H) AS INSP_07H,
        SUM(QTY_08H) AS INSP_08H, SUM(QTY_09H) AS INSP_09H, SUM(QTY_10H) AS INSP_10H, SUM(QTY_11H) AS INSP_11H,
        SUM(QTY_12H) AS INSP_12H, SUM(QTY_13H) AS INSP_13H, SUM(QTY_14H) AS INSP_14H, SUM(QTY_15H) AS INSP_15H,
        SUM(QTY_16H) AS INSP_16H, SUM(QTY_17H) AS INSP_17H, SUM(QTY_18H) AS INSP_18H, SUM(QTY_19H) AS INSP_19H,
        SUM(QTY_20H) AS INSP_20H, SUM(QTY_21H) AS INSP_21H, SUM(QTY_22H) AS INSP_22H, SUM(QTY_23H) AS INSP_23H,
        (
            SUM(COALESCE(QTY_00H,0)) + SUM(COALESCE(QTY_01H,0)) + SUM(COALESCE(QTY_02H,0)) + SUM(COALESCE(QTY_03H,0)) +
            SUM(COALESCE(QTY_04H,0)) + SUM(COALESCE(QTY_05H,0)) + SUM(COALESCE(QTY_06H,0)) + SUM(COALESCE(QTY_07H,0)) +
            SUM(COALESCE(QTY_08H,0)) + SUM(COALESCE(QTY_09H,0)) + SUM(COALESCE(QTY_10H,0)) + SUM(COALESCE(QTY_11H,0)) +
            SUM(COALESCE(QTY_12H,0)) + SUM(COALESCE(QTY_13H,0)) + SUM(COALESCE(QTY_14H,0)) + SUM(COALESCE(QTY_15H,0)) +
            SUM(COALESCE(QTY_16H,0)) + SUM(COALESCE(QTY_17H,0)) + SUM(COALESCE(QTY_18H,0)) + SUM(COALESCE(QTY_19H,0)) +
            SUM(COALESCE(QTY_20H,0)) + SUM(COALESCE(QTY_21H,0)) + SUM(COALESCE(QTY_22H,0)) + SUM(COALESCE(QTY_23H,0))
        ) AS INSP_TOTAL
    FROM (
        SELECT
            CASE WHEN HOUR_CD = '00' THEN QTY END AS QTY_00H,
            CASE WHEN HOUR_CD = '01' THEN QTY END AS QTY_01H,
            CASE WHEN HOUR_CD = '02' THEN QTY END AS QTY_02H,
            CASE WHEN HOUR_CD = '03' THEN QTY END AS QTY_03H,
            CASE WHEN HOUR_CD = '04' THEN QTY END AS QTY_04H,
            CASE WHEN HOUR_CD = '05' THEN QTY END AS QTY_05H,
            CASE WHEN HOUR_CD = '06' THEN QTY END AS QTY_06H,
            CASE WHEN HOUR_CD = '07' THEN QTY END AS QTY_07H,
            CASE WHEN HOUR_CD = '08' THEN QTY END AS QTY_08H,
            CASE WHEN HOUR_CD = '09' THEN QTY END AS QTY_09H,
            CASE WHEN HOUR_CD = '10' THEN QTY END AS QTY_10H,
            CASE WHEN HOUR_CD = '11' THEN QTY END AS QTY_11H,
            CASE WHEN HOUR_CD = '12' THEN QTY END AS QTY_12H,
            CASE WHEN HOUR_CD = '13' THEN QTY END AS QTY_13H,
            CASE WHEN HOUR_CD = '14' THEN QTY END AS QTY_14H,
            CASE WHEN HOUR_CD = '15' THEN QTY END AS QTY_15H,
            CASE WHEN HOUR_CD = '16' THEN QTY END AS QTY_16H,
            CASE WHEN HOUR_CD = '17' THEN QTY END AS QTY_17H,
            CASE WHEN HOUR_CD = '18' THEN QTY END AS QTY_18H,
            CASE WHEN HOUR_CD = '19' THEN QTY END AS QTY_19H,
            CASE WHEN HOUR_CD = '20' THEN QTY END AS QTY_20H,
            CASE WHEN HOUR_CD = '21' THEN QTY END AS QTY_21H,
            CASE WHEN HOUR_CD = '22' THEN QTY END AS QTY_22H,
            CASE WHEN HOUR_CD = '23' THEN QTY END AS QTY_23H
        FROM (
            SELECT
                HOUR_CD,
                COUNT(DISTINCT (UCC_NO || INSPECT_NO)) AS QTY
            FROM quality.dmqm_hfpa_insp
            WHERE PLANT_CD = $1
              AND INSPECT_DATE = $2
              AND work_center = $3
              AND line_cd = $4
            GROUP BY HOUR_CD
        ) AS t
    ) AS x
),
DEFE_DATA AS (
    SELECT
        SUM(QTY_00H) AS DEFE_00H, SUM(QTY_01H) AS DEFE_01H, SUM(QTY_02H) AS DEFE_02H, SUM(QTY_03H) AS DEFE_03H,
        SUM(QTY_04H) AS DEFE_04H, SUM(QTY_05H) AS DEFE_05H, SUM(QTY_06H) AS DEFE_06H, SUM(QTY_07H) AS DEFE_07H,
        SUM(QTY_08H) AS DEFE_08H, SUM(QTY_09H) AS DEFE_09H, SUM(QTY_10H) AS DEFE_10H, SUM(QTY_11H) AS DEFE_11H,
        SUM(QTY_12H) AS DEFE_12H, SUM(QTY_13H) AS DEFE_13H, SUM(QTY_14H) AS DEFE_14H, SUM(QTY_15H) AS DEFE_15H,
        SUM(QTY_16H) AS DEFE_16H, SUM(QTY_17H) AS DEFE_17H, SUM(QTY_18H) AS DEFE_18H, SUM(QTY_19H) AS DEFE_19H,
        SUM(QTY_20H) AS DEFE_20H, SUM(QTY_21H) AS DEFE_21H, SUM(QTY_22H) AS DEFE_22H, SUM(QTY_23H) AS DEFE_23H,
        (
            SUM(COALESCE(QTY_00H,0)) + SUM(COALESCE(QTY_01H,0)) + SUM(COALESCE(QTY_02H,0)) + SUM(COALESCE(QTY_03H,0)) +
            SUM(COALESCE(QTY_04H,0)) + SUM(COALESCE(QTY_05H,0)) + SUM(COALESCE(QTY_06H,0)) + SUM(COALESCE(QTY_07H,0)) +
            SUM(COALESCE(QTY_08H,0)) + SUM(COALESCE(QTY_09H,0)) + SUM(COALESCE(QTY_10H,0)) + SUM(COALESCE(QTY_11H,0)) +
            SUM(COALESCE(QTY_12H,0)) + SUM(COALESCE(QTY_13H,0)) + SUM(COALESCE(QTY_14H,0)) + SUM(COALESCE(QTY_15H,0)) +
            SUM(COALESCE(QTY_16H,0)) + SUM(COALESCE(QTY_17H,0)) + SUM(COALESCE(QTY_18H,0)) + SUM(COALESCE(QTY_19H,0)) +
            SUM(COALESCE(QTY_20H,0)) + SUM(COALESCE(QTY_21H,0)) + SUM(COALESCE(QTY_22H,0)) + SUM(COALESCE(QTY_23H,0))
        ) AS DEFE_TOTAL
    FROM (
        SELECT
            CASE WHEN HOUR_CD = '00' THEN QTY END AS QTY_00H,
            CASE WHEN HOUR_CD = '01' THEN QTY END AS QTY_01H,
            CASE WHEN HOUR_CD = '02' THEN QTY END AS QTY_02H,
            CASE WHEN HOUR_CD = '03' THEN QTY END AS QTY_03H,
            CASE WHEN HOUR_CD = '04' THEN QTY END AS QTY_04H,
            CASE WHEN HOUR_CD = '05' THEN QTY END AS QTY_05H,
            CASE WHEN HOUR_CD = '06' THEN QTY END AS QTY_06H,
            CASE WHEN HOUR_CD = '07' THEN QTY END AS QTY_07H,
            CASE WHEN HOUR_CD = '08' THEN QTY END AS QTY_08H,
            CASE WHEN HOUR_CD = '09' THEN QTY END AS QTY_09H,
            CASE WHEN HOUR_CD = '10' THEN QTY END AS QTY_10H,
            CASE WHEN HOUR_CD = '11' THEN QTY END AS QTY_11H,
            CASE WHEN HOUR_CD = '12' THEN QTY END AS QTY_12H,
            CASE WHEN HOUR_CD = '13' THEN QTY END AS QTY_13H,
            CASE WHEN HOUR_CD = '14' THEN QTY END AS QTY_14H,
            CASE WHEN HOUR_CD = '15' THEN QTY END AS QTY_15H,
            CASE WHEN HOUR_CD = '16' THEN QTY END AS QTY_16H,
            CASE WHEN HOUR_CD = '17' THEN QTY END AS QTY_17H,
            CASE WHEN HOUR_CD = '18' THEN QTY END AS QTY_18H,
            CASE WHEN HOUR_CD = '19' THEN QTY END AS QTY_19H,
            CASE WHEN HOUR_CD = '20' THEN QTY END AS QTY_20H,
            CASE WHEN HOUR_CD = '21' THEN QTY END AS QTY_21H,
            CASE WHEN HOUR_CD = '22' THEN QTY END AS QTY_22H,
            CASE WHEN HOUR_CD = '23' THEN QTY END AS QTY_23H
        FROM (
            SELECT
                HOUR_CD,
                SUM(COALESCE(DEFECT_QTY,0)) AS QTY
            FROM quality.dmqm_hfpa_insp
            WHERE PLANT_CD = $1
              AND INSPECT_DATE = $2
              AND work_center = $3
              AND line_cd = $4
            GROUP BY HOUR_CD
        ) AS t
    ) AS x
),
PROD_DATA AS (
    SELECT
        SUM(QTY_00H) AS PROD_00H, SUM(QTY_01H) AS PROD_01H, SUM(QTY_02H) AS PROD_02H, SUM(QTY_03H) AS PROD_03H,
        SUM(QTY_04H) AS PROD_04H, SUM(QTY_05H) AS PROD_05H, SUM(QTY_06H) AS PROD_06H, SUM(QTY_07H) AS PROD_07H,
        SUM(QTY_08H) AS PROD_08H, SUM(QTY_09H) AS PROD_09H, SUM(QTY_10H) AS PROD_10H, SUM(QTY_11H) AS PROD_11H,
        SUM(QTY_12H) AS PROD_12H, SUM(QTY_13H) AS PROD_13H, SUM(QTY_14H) AS PROD_14H, SUM(QTY_15H) AS PROD_15H,
        SUM(QTY_16H) AS PROD_16H, SUM(QTY_17H) AS PROD_17H, SUM(QTY_18H) AS PROD_18H, SUM(QTY_19H) AS PROD_19H,
        SUM(QTY_20H) AS PROD_20H, SUM(QTY_21H) AS PROD_21H, SUM(QTY_22H) AS PROD_22H, SUM(QTY_23H) AS PROD_23H,
        (
            SUM(COALESCE(QTY_00H,0)) + SUM(COALESCE(QTY_01H,0)) + SUM(COALESCE(QTY_02H,0)) + SUM(COALESCE(QTY_03H,0)) +
            SUM(COALESCE(QTY_04H,0)) + SUM(COALESCE(QTY_05H,0)) + SUM(COALESCE(QTY_06H,0)) + SUM(COALESCE(QTY_07H,0)) +
            SUM(COALESCE(QTY_08H,0)) + SUM(COALESCE(QTY_09H,0)) + SUM(COALESCE(QTY_10H,0)) + SUM(COALESCE(QTY_11H,0)) +
            SUM(COALESCE(QTY_12H,0)) + SUM(COALESCE(QTY_13H,0)) + SUM(COALESCE(QTY_14H,0)) + SUM(COALESCE(QTY_15H,0)) +
            SUM(COALESCE(QTY_16H,0)) + SUM(COALESCE(QTY_17H,0)) + SUM(COALESCE(QTY_18H,0)) + SUM(COALESCE(QTY_19H,0)) +
            SUM(COALESCE(QTY_20H,0)) + SUM(COALESCE(QTY_21H,0)) + SUM(COALESCE(QTY_22H,0)) + SUM(COALESCE(QTY_23H,0))
        ) AS PROD_TOTAL
    FROM (
        SELECT
            CASE WHEN HOUR_CD = '00' THEN QTY END AS QTY_00H,
            CASE WHEN HOUR_CD = '01' THEN QTY END AS QTY_01H,
            CASE WHEN HOUR_CD = '02' THEN QTY END AS QTY_02H,
            CASE WHEN HOUR_CD = '03' THEN QTY END AS QTY_03H,
            CASE WHEN HOUR_CD = '04' THEN QTY END AS QTY_04H,
            CASE WHEN HOUR_CD = '05' THEN QTY END AS QTY_05H,
            CASE WHEN HOUR_CD = '06' THEN QTY END AS QTY_06H,
            CASE WHEN HOUR_CD = '07' THEN QTY END AS QTY_07H,
            CASE WHEN HOUR_CD = '08' THEN QTY END AS QTY_08H,
            CASE WHEN HOUR_CD = '09' THEN QTY END AS QTY_09H,
            CASE WHEN HOUR_CD = '10' THEN QTY END AS QTY_10H,
            CASE WHEN HOUR_CD = '11' THEN QTY END AS QTY_11H,
            CASE WHEN HOUR_CD = '12' THEN QTY END AS QTY_12H,
            CASE WHEN HOUR_CD = '13' THEN QTY END AS QTY_13H,
            CASE WHEN HOUR_CD = '14' THEN QTY END AS QTY_14H,
            CASE WHEN HOUR_CD = '15' THEN QTY END AS QTY_15H,
            CASE WHEN HOUR_CD = '16' THEN QTY END AS QTY_16H,
            CASE WHEN HOUR_CD = '17' THEN QTY END AS QTY_17H,
            CASE WHEN HOUR_CD = '18' THEN QTY END AS QTY_18H,
            CASE WHEN HOUR_CD = '19' THEN QTY END AS QTY_19H,
            CASE WHEN HOUR_CD = '20' THEN QTY END AS QTY_20H,
            CASE WHEN HOUR_CD = '21' THEN QTY END AS QTY_21H,
            CASE WHEN HOUR_CD = '22' THEN QTY END AS QTY_22H,
            CASE WHEN HOUR_CD = '23' THEN QTY END AS QTY_23H
        FROM (
            SELECT SUBSTR(scan_time, 1, 2) AS hour_cd,
                   SUM(scan_qty) AS qty
            FROM mes.dmpd_misspacking_scan
            WHERE scan_date = $2
              AND work_center = $3
              AND zcf_line_cd = $4
            GROUP BY SUBSTR(scan_time, 1, 2)
        ) AS t
    ) AS x
),
DEFE_CNT AS (
    SELECT
        COALESCE(DEFECT_NM, 'Defect Total') AS DEFECT_NM,
        SUM(QTY_00H) AS CNT_00H, SUM(QTY_01H) AS CNT_01H, SUM(QTY_02H) AS CNT_02H, SUM(QTY_03H) AS CNT_03H, SUM(QTY_04H) AS CNT_04H,
        SUM(QTY_05H) AS CNT_05H, SUM(QTY_06H) AS CNT_06H, SUM(QTY_07H) AS CNT_07H, SUM(QTY_08H) AS CNT_08H, SUM(QTY_09H) AS CNT_09H,
        SUM(QTY_10H) AS CNT_10H, SUM(QTY_11H) AS CNT_11H, SUM(QTY_12H) AS CNT_12H, SUM(QTY_13H) AS CNT_13H, SUM(QTY_14H) AS CNT_14H,
        SUM(QTY_15H) AS CNT_15H, SUM(QTY_16H) AS CNT_16H, SUM(QTY_17H) AS CNT_17H, SUM(QTY_18H) AS CNT_18H, SUM(QTY_19H) AS CNT_19H,
        SUM(QTY_20H) AS CNT_20H, SUM(QTY_21H) AS CNT_21H, SUM(QTY_22H) AS CNT_22H, SUM(QTY_23H) AS CNT_23H,
        (
            SUM(COALESCE(QTY_00H,0)) + SUM(COALESCE(QTY_01H,0)) + SUM(COALESCE(QTY_02H,0)) + SUM(COALESCE(QTY_03H,0)) +
            SUM(COALESCE(QTY_04H,0)) + SUM(COALESCE(QTY_05H,0)) + SUM(COALESCE(QTY_06H,0)) + SUM(COALESCE(QTY_07H,0)) +
            SUM(COALESCE(QTY_08H,0)) + SUM(COALESCE(QTY_09H,0)) + SUM(COALESCE(QTY_10H,0)) + SUM(COALESCE(QTY_11H,0)) +
            SUM(COALESCE(QTY_12H,0)) + SUM(COALESCE(QTY_13H,0)) + SUM(COALESCE(QTY_14H,0)) + SUM(COALESCE(QTY_15H,0)) +
            SUM(COALESCE(QTY_16H,0)) + SUM(COALESCE(QTY_17H,0)) + SUM(COALESCE(QTY_18H,0)) + SUM(COALESCE(QTY_19H,0)) +
            SUM(COALESCE(QTY_20H,0)) + SUM(COALESCE(QTY_21H,0)) + SUM(COALESCE(QTY_22H,0)) + SUM(COALESCE(QTY_23H,0))
        ) AS CNT_TOTAL
    FROM (
        SELECT
            DEFECT_NM,
            CASE WHEN HOUR_CD = '00' THEN QTY END AS QTY_00H,
            CASE WHEN HOUR_CD = '01' THEN QTY END AS QTY_01H,
            CASE WHEN HOUR_CD = '02' THEN QTY END AS QTY_02H,
            CASE WHEN HOUR_CD = '03' THEN QTY END AS QTY_03H,
            CASE WHEN HOUR_CD = '04' THEN QTY END AS QTY_04H,
            CASE WHEN HOUR_CD = '05' THEN QTY END AS QTY_05H,
            CASE WHEN HOUR_CD = '06' THEN QTY END AS QTY_06H,
            CASE WHEN HOUR_CD = '07' THEN QTY END AS QTY_07H,
            CASE WHEN HOUR_CD = '08' THEN QTY END AS QTY_08H,
            CASE WHEN HOUR_CD = '09' THEN QTY END AS QTY_09H,
            CASE WHEN HOUR_CD = '10' THEN QTY END AS QTY_10H,
            CASE WHEN HOUR_CD = '11' THEN QTY END AS QTY_11H,
            CASE WHEN HOUR_CD = '12' THEN QTY END AS QTY_12H,
            CASE WHEN HOUR_CD = '13' THEN QTY END AS QTY_13H,
            CASE WHEN HOUR_CD = '14' THEN QTY END AS QTY_14H,
            CASE WHEN HOUR_CD = '15' THEN QTY END AS QTY_15H,
            CASE WHEN HOUR_CD = '16' THEN QTY END AS QTY_16H,
            CASE WHEN HOUR_CD = '17' THEN QTY END AS QTY_17H,
            CASE WHEN HOUR_CD = '18' THEN QTY END AS QTY_18H,
            CASE WHEN HOUR_CD = '19' THEN QTY END AS QTY_19H,
            CASE WHEN HOUR_CD = '20' THEN QTY END AS QTY_20H,
            CASE WHEN HOUR_CD = '21' THEN QTY END AS QTY_21H,
            CASE WHEN HOUR_CD = '22' THEN QTY END AS QTY_22H,
            CASE WHEN HOUR_CD = '23' THEN QTY END AS QTY_23H
        FROM (
            SELECT
                A.DEFECT_NM,
                B.HOUR_CD,
                B.QTY
            FROM (
                SELECT SUB_CODE AS DEFECT_CD, CODE_NAME AS DEFECT_NM
                FROM quality.dmbs_code_master_temp
                WHERE plant_cd = $1
                  AND CODE_CLASS_CD = 'HFPA'
                ORDER BY SUB_CODE
            ) AS A
            LEFT JOIN (
                SELECT DEFECT_CD, HOUR_CD, COUNT(*) AS QTY
                FROM quality.dmqm_hfpa_insp
                WHERE PLANT_CD = $1
                  AND INSPECT_DATE = $2
                  AND work_center = $3
                  AND line_cd = $4
                GROUP BY DEFECT_CD, HOUR_CD
            ) AS B
              ON A.DEFECT_CD = REPLACE(B.DEFECT_CD, 'FGA', 'HFPA')
        ) AS t
    ) AS x
    GROUP BY ROLLUP (DEFECT_NM)
)
SELECT
    DEFECT_NM AS DIV,
    TO_CHAR(CNT_00H, '990') AS "H_00", TO_CHAR(CNT_01H, '990') AS "H_01", TO_CHAR(CNT_02H, '990') AS "H_02", TO_CHAR(CNT_03H, '990') AS "H_03", TO_CHAR(CNT_04H, '990') AS "H_04",
    TO_CHAR(CNT_05H, '990') AS "H_05", TO_CHAR(CNT_06H, '990') AS "H_06", TO_CHAR(CNT_07H, '990') AS "H_07", TO_CHAR(CNT_08H, '990') AS "H_08",
    TO_CHAR(CNT_09H, '990') AS "H_09", TO_CHAR(CNT_10H, '990') AS "H_10", TO_CHAR(CNT_11H, '990') AS "H_11", TO_CHAR(CNT_12H, '990') AS "H_12",
    TO_CHAR(CNT_13H, '990') AS "H_13", TO_CHAR(CNT_14H, '990') AS "H_14", TO_CHAR(CNT_15H, '990') AS "H_15", TO_CHAR(CNT_16H, '990') AS "H_16",
    TO_CHAR(CNT_17H, '990') AS "H_17", TO_CHAR(CNT_18H, '990') AS "H_18", TO_CHAR(CNT_19H, '990') AS "H_19", TO_CHAR(CNT_20H, '990') AS "H_20",
    TO_CHAR(CNT_21H, '990') AS "H_21", TO_CHAR(CNT_22H, '990') AS "H_22", TO_CHAR(CNT_23H, '990') AS "H_23",
    TO_CHAR(CNT_TOTAL, '990') AS "TOTAL"
FROM DEFE_CNT
UNION ALL
SELECT
    'Defective Total' AS DIV,
    TO_CHAR(INSP_00H, '990'), TO_CHAR(INSP_01H, '990'), TO_CHAR(INSP_02H, '990'), TO_CHAR(INSP_03H, '990'), TO_CHAR(INSP_04H, '990'),
    TO_CHAR(INSP_05H, '990'), TO_CHAR(INSP_06H, '990'), TO_CHAR(INSP_07H, '990'), TO_CHAR(INSP_08H, '990'), TO_CHAR(INSP_09H, '990'),
    TO_CHAR(INSP_10H, '990'), TO_CHAR(INSP_11H, '990'), TO_CHAR(INSP_12H, '990'), TO_CHAR(INSP_13H, '990'), TO_CHAR(INSP_14H, '990'),
    TO_CHAR(INSP_15H, '990'), TO_CHAR(INSP_16H, '990'), TO_CHAR(INSP_17H, '990'), TO_CHAR(INSP_18H, '990'), TO_CHAR(INSP_19H, '990'),
    TO_CHAR(INSP_20H, '990'), TO_CHAR(INSP_21H, '990'), TO_CHAR(INSP_22H, '990'), TO_CHAR(INSP_23H, '990'),
    TO_CHAR(INSP_TOTAL, '990')
FROM DEFECTIVE_DATA d
UNION ALL
SELECT
    'Defective Rate' AS DIV,
    CASE WHEN COALESCE(dd.INSP_00H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_00H,0)::numeric / COALESCE(dd.INSP_00H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_01H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_01H,0)::numeric / COALESCE(dd.INSP_01H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_02H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_02H,0)::numeric / COALESCE(dd.INSP_02H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_03H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_03H,0)::numeric / COALESCE(dd.INSP_03H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_04H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_04H,0)::numeric / COALESCE(dd.INSP_04H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_05H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_05H,0)::numeric / COALESCE(dd.INSP_05H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_06H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_06H,0)::numeric / COALESCE(dd.INSP_06H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_07H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_07H,0)::numeric / COALESCE(dd.INSP_07H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_08H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_08H,0)::numeric / COALESCE(dd.INSP_08H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_09H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_09H,0)::numeric / COALESCE(dd.INSP_09H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_10H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_10H,0)::numeric / COALESCE(dd.INSP_10H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_11H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_11H,0)::numeric / COALESCE(dd.INSP_11H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_12H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_12H,0)::numeric / COALESCE(dd.INSP_12H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_13H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_13H,0)::numeric / COALESCE(dd.INSP_13H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_14H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_14H,0)::numeric / COALESCE(dd.INSP_14H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_15H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_15H,0)::numeric / COALESCE(dd.INSP_15H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_16H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_16H,0)::numeric / COALESCE(dd.INSP_16H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_17H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_17H,0)::numeric / COALESCE(dd.INSP_17H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_18H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_18H,0)::numeric / COALESCE(dd.INSP_18H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_19H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_19H,0)::numeric / COALESCE(dd.INSP_19H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_20H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_20H,0)::numeric / COALESCE(dd.INSP_20H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_21H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_21H,0)::numeric / COALESCE(dd.INSP_21H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_22H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_22H,0)::numeric / COALESCE(dd.INSP_22H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_23H,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_23H,0)::numeric / COALESCE(dd.INSP_23H,0)::numeric * 100), 2), '990.0') END,
    CASE WHEN COALESCE(dd.INSP_TOTAL,0) = 0 THEN '0'
         ELSE TO_CHAR(ROUND((COALESCE(de.DEFE_TOTAL,0)::numeric / COALESCE(dd.INSP_TOTAL,0)::numeric * 100), 2), '990.0') END
FROM INSP_DATA dd
CROSS JOIN DEFE_DATA de
UNION ALL
SELECT
    'Audit Total' AS DIV,
    TO_CHAR(i.INSP_00H, '990'), TO_CHAR(i.INSP_01H, '990'), TO_CHAR(i.INSP_02H, '990'), TO_CHAR(i.INSP_03H, '990'), TO_CHAR(i.INSP_04H, '990'),
    TO_CHAR(i.INSP_05H, '990'), TO_CHAR(i.INSP_06H, '990'), TO_CHAR(i.INSP_07H, '990'), TO_CHAR(i.INSP_08H, '990'), TO_CHAR(i.INSP_09H, '990'),
    TO_CHAR(i.INSP_10H, '990'), TO_CHAR(i.INSP_11H, '990'), TO_CHAR(i.INSP_12H, '990'), TO_CHAR(i.INSP_13H, '990'), TO_CHAR(i.INSP_14H, '990'),
    TO_CHAR(i.INSP_15H, '990'), TO_CHAR(i.INSP_16H, '990'), TO_CHAR(i.INSP_17H, '990'), TO_CHAR(i.INSP_18H, '990'), TO_CHAR(i.INSP_19H, '990'),
    TO_CHAR(i.INSP_20H, '990'), TO_CHAR(i.INSP_21H, '990'), TO_CHAR(i.INSP_22H, '990'), TO_CHAR(i.INSP_23H, '990'),
    TO_CHAR(i.INSP_TOTAL, '990')
FROM INSP_DATA i
UNION ALL
SELECT
    'Production Qty' AS DIV,
    TO_CHAR(p.PROD_00H, '990'), TO_CHAR(p.PROD_01H, '990'), TO_CHAR(p.PROD_02H, '990'), TO_CHAR(p.PROD_03H, '990'), TO_CHAR(p.PROD_04H, '990'),
    TO_CHAR(p.PROD_05H, '990'), TO_CHAR(p.PROD_06H, '990'), TO_CHAR(p.PROD_07H, '990'), TO_CHAR(p.PROD_08H, '990'), TO_CHAR(p.PROD_09H, '990'),
    TO_CHAR(p.PROD_10H, '990'), TO_CHAR(p.PROD_11H, '990'), TO_CHAR(p.PROD_12H, '990'), TO_CHAR(p.PROD_13H, '990'), TO_CHAR(p.PROD_14H, '990'),
    TO_CHAR(p.PROD_15H, '990'), TO_CHAR(p.PROD_16H, '990'), TO_CHAR(p.PROD_17H, '990'), TO_CHAR(p.PROD_18H, '990'), TO_CHAR(p.PROD_19H, '990'),
    TO_CHAR(p.PROD_20H, '990'), TO_CHAR(p.PROD_21H, '990'), TO_CHAR(p.PROD_22H, '990'), TO_CHAR(p.PROD_23H, '990'),
    TO_CHAR(p.PROD_TOTAL, '990')
FROM PROD_DATA p;
  `;

  const { rows } = await client.query(sql, params);
  return rows;
}
